#### Consider the below code to answer further questions:

In [1]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

yes,there is difference in the datatypes of variables_list and array_list.

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

In [5]:
array_list.dtype

dtype('<U1')

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [6]:
print("datatypes of elements in list\n")
for i in list_:
    print(type(i),i)
print("datatypes of elements in array_list\n")
for i in array_list:
    print(type(i),i)

datatypes of elements in list

<class 'str'> 1
<class 'str'> 2
<class 'str'> 3
<class 'str'> 4
<class 'str'> 5
datatypes of elements in array_list

<class 'numpy.str_'> 1
<class 'numpy.str_'> 2
<class 'numpy.str_'> 3
<class 'numpy.str_'> 4
<class 'numpy.str_'> 5


#### Q3. Considering the following changes in the variable, array_list:

In [7]:
array_list = np.array(object = list_, dtype = int)

In [8]:
array_list

array([1, 2, 3, 4, 5])

#### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

yes ,there will be difference in  the data type of the elements present in both the variables, list_ and arra_list

In [9]:
type(list_)

list

In [10]:
type(array_list)

numpy.ndarray

#### Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [11]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [12]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

#### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [13]:
num_array.shape

(2, 3)

In [14]:
num_array.size

6

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [15]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
import numpy as np
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])